# Dev image with Python and Node.js installed
FROM python:3.14.0-slim-bookworm

RUN apt-get -y update; apt-get -y install curl

RUN curl -sL https://deb.nodesource.com/setup_25.x | bash
RUN apt-get install -y nodejs

RUN python -m pip install --upgrade pip

CMD ["tail", "-f", "/dev/null"]