# Generated by Django 5.2.8 on 2025-12-17 16:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planner', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trainingplan',
            name='creation_date',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
