# Generated by Django 5.2.8 on 2025-12-02 13:27

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_of_birth', models.DateField()),
                ('sex', models.CharField(choices=[('M', 'male'), ('F', 'female'), ('P', 'prefer not to say')], max_length=14)),
                ('height_cm', models.FloatField()),
                ('weight_kg', models.FloatField()),
                ('fitness_level', models.CharField(choices=[('B', 'beginner'), ('I', 'intermediate'), ('A', 'advanced'), ('E', 'elite')], max_length=12)),
                ('running_experience', models.CharField(choices=[('B', 'beginner'), ('I', 'intermediate'), ('A', 'advanced'), ('E', 'elite')], max_length=12)),
                ('injury_history', models.TextField(blank=True, null=True)),
                ('medical_conditions', models.TextField(blank=True, null=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
