# Generated by Django 5.2.8 on 2025-12-10 11:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_userprofile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='injury_history',
            field=models.TextField(blank=True, max_length=400, null=True),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='medical_conditions',
            field=models.TextField(blank=True, max_length=400, null=True),
        ),
    ]
